nome = input('Qual o seu nome? ')
idade = input('Qual a sua idade? ')
peso = input('Qual o seu peso? ')
print(nome, idade, peso)
input('==== DESAFIO ====')
nome = input('Qual o seu nome? ')
input(f'Olá {nome}! Prazer em te conhecer!')